/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secureaccess;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author vvtat
 */
public class AddPasswordGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddPasswordGUI.class.getName());

    private final SessionManager sessionManager;
    private final String userEmail;
    private final DashboardGUI parentDashboard; // Reference to refresh the list
    /**
     * Creates new form AddPasswordGUI
     */
    public AddPasswordGUI() {
        this.sessionManager = null;
        this.userEmail = null;
        this.parentDashboard = null;
        setupPasswordListener();
        initComponents();
    }
    
    //Creates new form AddPasswordGUI with session information. 
    public AddPasswordGUI(SessionManager sm, String userEmail, DashboardGUI parent) {
        this.sessionManager = sm;
        this.userEmail = userEmail;
        this.parentDashboard = parent;
        initComponents();
        this.setLocationRelativeTo(null); // Center the window
        // Set initial state for password field to hide characters
        passwordTF.setEchoChar('*'); 
        setupPasswordListener(); // Setup listener for strength check
    }
    
    //method to handle password strength checking
    private void setupPasswordListener() {
        passwordTF.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                checkPasswordStrength();
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                checkPasswordStrength();
            }
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                checkPasswordStrength();
            }
        });
        // Initial check for default text
        checkPasswordStrength(); 
    }
    
    //Calculates and updates the password strength progress bar and label.
    private void checkPasswordStrength() {
        String password = new String(passwordTF.getPassword());
        if (password.isEmpty()) {
            pswStrengthProgressBar.setValue(0);
            pswStrengthLBL.setText("Strength: N/A");
            pswStrengthProgressBar.setForeground(Color.GRAY);
            return;
        }

        int score = PasswordStrengthUtil.calculateStrength(password); // Requires PasswordStrengthUtil
        pswStrengthProgressBar.setValue(score);

        // Update color and label based on score (0-100)
        if (score < 25) {
            pswStrengthProgressBar.setForeground(Color.RED);
            pswStrengthLBL.setText("Strength: Weak");
        } else if (score < 50) {
            pswStrengthProgressBar.setForeground(Color.ORANGE);
            pswStrengthLBL.setText("Strength: Fair");
        } else if (score < 75) {
            pswStrengthProgressBar.setForeground(Color.YELLOW);
            pswStrengthLBL.setText("Strength: Good");
        } else {
            pswStrengthProgressBar.setForeground(Color.GREEN);
            pswStrengthLBL.setText("Strength: Strong");
        }
    }
    
    // Helper method to transition back to the dashboard
    private void returnToDashboard() {
        if (sessionManager != null) sessionManager.touch();
        this.dispose();
        if (parentDashboard != null) {
            parentDashboard.refreshPasswordList();
            parentDashboard.setVisible(true);
        } else {
             // Fallback if accessed directly (e.g., from main())
             new DashboardGUI(sessionManager, userEmail).setVisible(true);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        backBTN = new javax.swing.JButton();
        titleLBL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        sitenameLBL = new javax.swing.JLabel();
        sitenameTF = new javax.swing.JTextField();
        usernameLBL = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        passwordLBL = new javax.swing.JLabel();
        urlTF = new javax.swing.JTextField();
        urlLBL = new javax.swing.JLabel();
        passwordTF = new javax.swing.JPasswordField();
        categoryLBL = new javax.swing.JLabel();
        categoryTF = new javax.swing.JTextField();
        viewBTN = new javax.swing.JRadioButton();
        generatePswBTN = new javax.swing.JButton();
        pswStrengthLBL = new javax.swing.JLabel();
        pswStrengthProgressBar = new javax.swing.JProgressBar();
        notesLBL = new javax.swing.JLabel();
        notesTF = new javax.swing.JTextField();
        saveBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 51, 51));

        backBTN.setBackground(new java.awt.Color(0, 51, 51));
        backBTN.setForeground(new java.awt.Color(255, 255, 255));
        backBTN.setText("← Back");
        backBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTNActionPerformed(evt);
            }
        });

        titleLBL.setFont(new java.awt.Font("HP Simplified Hans", 1, 24)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("Add Password");

        jPanel1.setBackground(new java.awt.Color(0, 91, 94));

        sitenameLBL.setForeground(new java.awt.Color(255, 255, 255));
        sitenameLBL.setText("Site name *");

        usernameLBL.setForeground(new java.awt.Color(255, 255, 255));
        usernameLBL.setText("Username/ Email *");

        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });

        passwordLBL.setForeground(new java.awt.Color(255, 255, 255));
        passwordLBL.setText("Password *");

        urlLBL.setForeground(new java.awt.Color(255, 255, 255));
        urlLBL.setText("URL (Option)");

        categoryLBL.setForeground(new java.awt.Color(255, 255, 255));
        categoryLBL.setText("Category (Optional)");

        viewBTN.setForeground(new java.awt.Color(255, 255, 255));
        viewBTN.setText("view");
        viewBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBTNActionPerformed(evt);
            }
        });

        generatePswBTN.setBackground(new java.awt.Color(0, 153, 153));
        generatePswBTN.setText("Generate");
        generatePswBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePswBTNActionPerformed(evt);
            }
        });

        pswStrengthLBL.setForeground(new java.awt.Color(255, 255, 255));
        pswStrengthLBL.setText("Strength :");

        notesLBL.setForeground(new java.awt.Color(255, 255, 255));
        notesLBL.setText("Notes (Optional)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLBL)
                            .addComponent(usernameLBL)
                            .addComponent(sitenameLBL)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(passwordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(viewBTN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(generatePswBTN))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(usernameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(sitenameTF, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswStrengthLBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswStrengthProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(categoryTF, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(categoryLBL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urlLBL, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urlTF))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notesLBL)
                            .addComponent(notesTF, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(sitenameLBL)
                .addGap(18, 18, 18)
                .addComponent(sitenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(usernameLBL)
                .addGap(18, 18, 18)
                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLBL)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(viewBTN)
                        .addComponent(generatePswBTN)
                        .addComponent(pswStrengthLBL))
                    .addComponent(pswStrengthProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(urlLBL)
                .addGap(18, 18, 18)
                .addComponent(urlTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(notesLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        saveBTN.setBackground(new java.awt.Color(0, 204, 204));
        saveBTN.setText("SAVE");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(backBTN)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(titleLBL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBTN)
                .addGap(21, 21, 21))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(backBTN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLBL)
                    .addComponent(saveBTN))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void backBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTNActionPerformed
        // TODO add your handling code here:
        returnToDashboard();
    }//GEN-LAST:event_backBTNActionPerformed

    private void viewBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBTNActionPerformed
        // TODO add your handling code here:
        if (sessionManager != null) sessionManager.touch();
        if (viewBTN.isSelected()) {
            passwordTF.setEchoChar((char) 0); // Show password
        } else {
            passwordTF.setEchoChar('*'); // Hide password
        }
    }//GEN-LAST:event_viewBTNActionPerformed

    private void generatePswBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePswBTNActionPerformed
        // TODO add your handling code here:
        if (sessionManager != null) sessionManager.touch();
        // Generates a 16-character strong password
        String generated = CryptoUtils.generateStrongPassword(16); // Requires CryptoUtils method
        passwordTF.setText(generated);
        checkPasswordStrength();
    }//GEN-LAST:event_generatePswBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        if (sessionManager != null) sessionManager.touch();
        
        String name = sitenameTF.getText().trim();
        String username = usernameTF.getText().trim();
        String password = new String(passwordTF.getPassword());
        String url = urlTF.getText().trim();
        String category = categoryTF.getText().trim();
        String notes = notesTF.getText().trim();
        
        // Basic Validation to check for all required inputs
        if (name.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Site Name, Username/Email, and Password are required.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        //Data Size Validation (Assuming MAX_LEN of 255 for  text fields)
        final int MAX_LEN = 255;
        if (name.length() > MAX_LEN) {
            JOptionPane.showMessageDialog(this, "Site Name must be under " + MAX_LEN + " characters.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (username.length() > MAX_LEN) {
            JOptionPane.showMessageDialog(this, "Username/Email must be under " + MAX_LEN + " characters.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (url.length() > MAX_LEN) {
            JOptionPane.showMessageDialog(this, "URL must be under " + MAX_LEN + " characters.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (category.length() > MAX_LEN) {
            JOptionPane.showMessageDialog(this, "Category must be under " + MAX_LEN + " characters.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (notes.length() > MAX_LEN) {
            JOptionPane.showMessageDialog(this, "Notes must be under " + MAX_LEN + " characters.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        //Password Strength Policy Enforcement (dictating Minimum score of 50)
        int strengthScore = PasswordStrengthUtil.calculateStrength(password);
        final int MIN_STRENGTH = 50; 
        
        if (strengthScore < MIN_STRENGTH) {
            JOptionPane.showMessageDialog(this, 
                "Password strength is too low. Please use a stronger password (Minimum score: " + MIN_STRENGTH + ").", 
                "Security Policy Violation", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 1. Encrypt the plaintext password
        String encryptedPassword = EncryptionUtil.encrypt(password);
        if (encryptedPassword == null) {
             JOptionPane.showMessageDialog(this, "Error encrypting password. Check application logs.", "Encryption Error", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        // 2. Create the PasswordEntry object
        PasswordEntry newEntry = new PasswordEntry(userEmail, name, username, url, category, notes);
        newEntry.setEncryptedPassword(encryptedPassword);
        newEntry.setNotes(notes);

        // 3. Save to database
        boolean success = DBhelper.savePassword(newEntry);
        
        if (success) {
            JOptionPane.showMessageDialog(this, "Password saved successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            returnToDashboard();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save password to database.", "DB Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddPasswordGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBTN;
    private javax.swing.JPanel background;
    private javax.swing.JLabel categoryLBL;
    private javax.swing.JTextField categoryTF;
    private javax.swing.JButton generatePswBTN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel notesLBL;
    private javax.swing.JTextField notesTF;
    private javax.swing.JLabel passwordLBL;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JLabel pswStrengthLBL;
    private javax.swing.JProgressBar pswStrengthProgressBar;
    private javax.swing.JButton saveBTN;
    private javax.swing.JLabel sitenameLBL;
    private javax.swing.JTextField sitenameTF;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JLabel urlLBL;
    private javax.swing.JTextField urlTF;
    private javax.swing.JLabel usernameLBL;
    private javax.swing.JTextField usernameTF;
    private javax.swing.JRadioButton viewBTN;
    // End of variables declaration//GEN-END:variables
}
