/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secureaccess;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author vvtat
 */
public class DashboardGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardGUI.class.getName());

    private final SessionManager sessionManager;
    private final String userEmail;
    private final DefaultListModel<PasswordEntry> passwordListModel;
    
    /**
     * Creates new form DashboardGUI
     */
    public DashboardGUI() {
        this.sessionManager = null;
        this.userEmail = null;
        this.passwordListModel = new DefaultListModel<>();
        initComponents();        
    }
    
    /**
     * Creates new form DashboardGUI with session information.
     * @param sm The active SessionManager instance.
     * @param username The username of the logged-in user.
     */
//    public DashboardGUI(SessionManager sm, String username) {
//        this.sessionManager = sm;
//        this.username = username;
//        initComponents();
//        // Update the title label to show the logged-in user
//        if (username != null && !username.isEmpty()) {
//            titleLBL.setText("Welcome to Secure Access, " + username + "!");
//        } else {
//            titleLBL.setText("Welcome to Secure Access!");
//        }
//        this.setLocationRelativeTo(null); // Center the window
//    }
    
    public DashboardGUI(SessionManager sm, String userEmail) {
        this.sessionManager = sm;
        this.userEmail = userEmail; // Use userEmail
        this.passwordListModel = new DefaultListModel<>(); // Initialize model
        initComponents();
        
        // Setup JList model and listener
        jList1.setModel(passwordListModel);
        jList1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList)evt.getSource();
                if (evt.getClickCount() == 2) { // Double-click to view password
                    int index = list.locationToIndex(evt.getPoint());
                    if (index >= 0) {
                        viewPassword(passwordListModel.getElementAt(index));
                    }
                }
            }
        });
        
        // Update the title label to show the logged-in user
        if (userEmail != null && !userEmail.isEmpty()) {
            titleLBL.setText("Welcome to Secure Access, " + userEmail + "!");
        } else {
            titleLBL.setText("Welcome to Secure Access!");
        }
        this.setLocationRelativeTo(null); // Center the window
        
        // Load passwords when dashboard opens
        refreshPasswordList(); 
    }
    
    /**
     * Loads all password entries for the current user and updates the JList.
     */
    public void refreshPasswordList() {
        sessionManager.touch(); // Keep session alive
        passwordListModel.clear();
        List<PasswordEntry> entries = DBhelper.getAllPasswords(userEmail); // userEmail is used here
        for (PasswordEntry entry : entries) {
            passwordListModel.addElement(entry);
        }
        titleLBL.setText("My Passwords (" + entries.size() + ")");
    }

    /**
     * Handles the display of a single password entry.
     * @param entry The PasswordEntry to view.
     */
    private void viewPassword(PasswordEntry entry) {
        // 1. Touch the session to reset the idle timer
        if (sessionManager != null) {
            sessionManager.touch();
        }
        
        // 2. Hide the current dashboard window
        this.setVisible(false);
        
        // 3. Show the ViewPassword GUI, passing the specific entry
        new ViewPasswordGUI(sessionManager, userEmail, entry, this).setVisible(true);
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidebarSeparator = new javax.swing.JSeparator();
        sidebarPanel = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        viewPasswordsBtn = new javax.swing.JButton();
        addPasswordBtn = new javax.swing.JButton();
        logoLBL = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        titleLBL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(0, 51, 51));
        background.setForeground(new java.awt.Color(255, 255, 255));

        sidebarSeparator.setOrientation(javax.swing.SwingConstants.VERTICAL);

        sidebarPanel.setBackground(new java.awt.Color(0, 91, 94));

        logoutBtn.setBackground(new java.awt.Color(0, 193, 193));
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        viewPasswordsBtn.setBackground(new java.awt.Color(0, 163, 163));
        viewPasswordsBtn.setText("My Passwords");
        viewPasswordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPasswordsBtnActionPerformed(evt);
            }
        });

        addPasswordBtn.setBackground(new java.awt.Color(0, 173, 173));
        addPasswordBtn.setText("Add Password");
        addPasswordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPasswordBtnActionPerformed(evt);
            }
        });

        logoLBL.setBackground(new java.awt.Color(255, 255, 255));
        logoLBL.setFont(new java.awt.Font("HP Simplified Hans", 1, 24)); // NOI18N
        logoLBL.setForeground(new java.awt.Color(255, 255, 255));
        logoLBL.setText("SECURE ACCESS");

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPasswordsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addComponent(addPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(sidebarPanelLayout.createSequentialGroup()
                        .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(logoutBtn))
                            .addGroup(sidebarPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(logoLBL)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(logoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(viewPasswordsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPasswordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(26, 26, 26))
        );

        titleLBL.setFont(new java.awt.Font("HP Simplified Hans", 1, 24)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(255, 255, 255));
        titleLBL.setText("My Passwords");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sidebarSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(titleLBL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(backgroundLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 4, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarSeparator)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleLBL)
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewPasswordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPasswordsBtnActionPerformed
        // TODO add your handling code here:
        // 1. Touch the session to reset the idle timer
        if (sessionManager != null) {
            sessionManager.touch();
        }
        
//        // 2. Hide the current dashboard window
//        this.setVisible(false);
//        
//        // 3. Show the ViewPasswords GUI
//        // Note: New GUI instance is created and linked to the active session
//        new ViewPasswordGUI(sessionManager, username).setVisible(true);
        refreshPasswordList();
        titleLBL.setText("My Passwords");

    }//GEN-LAST:event_viewPasswordsBtnActionPerformed

    private void addPasswordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPasswordBtnActionPerformed
        // TODO add your handling code here:
        // 1. Touch the session to reset the idle timer
        if (sessionManager != null) {
            sessionManager.touch();
        }
        
//        // 2. Hide the current dashboard window
//        this.setVisible(false);
//        
//        // 3. Show the AddPassword GUI
//        // Note: New GUI instance is created and linked to the active session
//        new AddPasswordGUI(sessionManager, username).setVisible(true);
    
        if (sessionManager != null) {
            sessionManager.touch();
        }
        this.setVisible(false);
        // Pass 'this' (the DashboardGUI) so AddPasswordGUI can call refreshPasswordList() on return
        new AddPasswordGUI(sessionManager, userEmail, this).setVisible(true);
    }//GEN-LAST:event_addPasswordBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        // 1. Stop the session (logs out the user and clears the token/idle monitor)
        if (sessionManager != null) {
            sessionManager.stop();
        }
        
        // 2. Hide the current dashboard window
        this.dispose();
        
        //3. Securely wipe the master encryption key from memory
        EncryptionUtil.wipeKey();
        
        // 4. Show the login GUI
        new loginGUI().setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPasswordBtn;
    private javax.swing.JPanel background;
    private javax.swing.JList<PasswordEntry> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoLBL;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JSeparator sidebarSeparator;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JButton viewPasswordsBtn;
    // End of variables declaration//GEN-END:variables
}
