/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package secureaccess;

import java.awt.Color;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;
//import secureaccessshauna.loginGUI;

/**
 *
 * @author shaun
 */
public class signupGUI extends javax.swing.JFrame {
    private String generateOTP;
    String verifyOTP = null;
    
    // @Virginiah: TEMPORARY STORAGE FIELDS
    private String tempName;
    private String tempEmail;
    private char[] tempPassword;

    /**
     * Creates new form signupGUI
     */
    public signupGUI() {
        DBhelper.initializeUsersTable();
        DBhelper.initializePasswordsTable();
        
        initComponents();
        verifyPanel.setVisible(false);
    }
        //generate a random one time password
        public String generateOTP(int length) {
        String digits = "0123456789";  //contains the numbers for the OTP
        Random random = new Random(); //generates a random OTP
        StringBuilder otp = new StringBuilder();  //stringbuilder gets the random numbers then combines them to create the OTP
        for (int i = 0; i < length; i++) {
            otp.append(digits.charAt(random.nextInt(digits.length())));
        }
        return otp.toString();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator8 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        submitJbtn = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        passwordJpf = new javax.swing.JPasswordField();
        signupJlbl = new javax.swing.JLabel();
        nameJlbl = new javax.swing.JLabel();
        passwordJlbl = new javax.swing.JLabel();
        emailJlbl = new javax.swing.JLabel();
        nameJtf = new javax.swing.JTextField();
        emailJtf = new javax.swing.JTextField();
        accountJbtn = new javax.swing.JButton();
        confirmpasswordJlbl = new javax.swing.JLabel();
        cpasswordJpf = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        welcomeJlbl = new javax.swing.JLabel();
        welcome2Jlbl = new javax.swing.JLabel();
        verifyPanel = new javax.swing.JPanel();
        emailJlbl2 = new javax.swing.JLabel();
        emailJlbl3 = new javax.swing.JLabel();
        emailJtf1 = new javax.swing.JTextField();
        verifyJbtn = new javax.swing.JButton();
        otpJlbl = new javax.swing.JLabel();
        otpJtf = new javax.swing.JTextField();
        sendOTPjbtn = new javax.swing.JButton();
        cancelJbtn = new javax.swing.JButton();

        jSeparator8.setBackground(new java.awt.Color(102, 66, 41));
        jSeparator8.setForeground(new java.awt.Color(102, 66, 41));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(227, 238, 212));

        jSeparator4.setBackground(new java.awt.Color(102, 66, 41));
        jSeparator4.setForeground(new java.awt.Color(102, 66, 41));

        submitJbtn.setBackground(new java.awt.Color(4, 50, 34));
        submitJbtn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        submitJbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitJbtn.setText("SUBMIT");
        submitJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJbtnActionPerformed(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(102, 66, 41));
        jSeparator7.setForeground(new java.awt.Color(102, 66, 41));

        passwordJpf.setBackground(new java.awt.Color(227, 238, 212));
        passwordJpf.setFont(new java.awt.Font("Corbel Light", 0, 12)); // NOI18N
        passwordJpf.setForeground(new java.awt.Color(102, 66, 41));
        passwordJpf.setText("Enter your password");
        passwordJpf.setBorder(null);
        passwordJpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordJpfFocusGained(evt);
            }
        });
        passwordJpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordJpfActionPerformed(evt);
            }
        });

        signupJlbl.setBackground(new java.awt.Color(227, 238, 212));
        signupJlbl.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        signupJlbl.setForeground(new java.awt.Color(102, 66, 41));
        signupJlbl.setText("Sign Up");

        nameJlbl.setBackground(new java.awt.Color(227, 238, 212));
        nameJlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        nameJlbl.setForeground(new java.awt.Color(102, 66, 41));
        nameJlbl.setText("NAME");

        passwordJlbl.setBackground(new java.awt.Color(227, 238, 212));
        passwordJlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        passwordJlbl.setForeground(new java.awt.Color(102, 66, 41));
        passwordJlbl.setText("PASSWORD");

        emailJlbl.setBackground(new java.awt.Color(227, 238, 212));
        emailJlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        emailJlbl.setForeground(new java.awt.Color(102, 66, 41));
        emailJlbl.setText("EMAIL");

        nameJtf.setBackground(new java.awt.Color(227, 238, 212));
        nameJtf.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        nameJtf.setForeground(new java.awt.Color(102, 66, 41));
        nameJtf.setText("Enter your name");
        nameJtf.setBorder(null);
        nameJtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameJtfFocusGained(evt);
            }
        });
        nameJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJtfActionPerformed(evt);
            }
        });

        emailJtf.setBackground(new java.awt.Color(227, 238, 212));
        emailJtf.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        emailJtf.setForeground(new java.awt.Color(102, 66, 41));
        emailJtf.setText("Enter your email");
        emailJtf.setBorder(null);
        emailJtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailJtfFocusGained(evt);
            }
        });
        emailJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJtfActionPerformed(evt);
            }
        });

        accountJbtn.setBackground(new java.awt.Color(227, 238, 212));
        accountJbtn.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        accountJbtn.setForeground(new java.awt.Color(102, 66, 41));
        accountJbtn.setText("Already have an account?");
        accountJbtn.setBorder(null);
        accountJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountJbtnActionPerformed(evt);
            }
        });

        confirmpasswordJlbl.setBackground(new java.awt.Color(227, 238, 212));
        confirmpasswordJlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        confirmpasswordJlbl.setForeground(new java.awt.Color(102, 66, 41));
        confirmpasswordJlbl.setText("CONFIRM PASSWORD");

        cpasswordJpf.setBackground(new java.awt.Color(227, 238, 212));
        cpasswordJpf.setFont(new java.awt.Font("Corbel Light", 0, 12)); // NOI18N
        cpasswordJpf.setForeground(new java.awt.Color(102, 66, 41));
        cpasswordJpf.setText("Enter your password");
        cpasswordJpf.setBorder(null);
        cpasswordJpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpasswordJpfFocusGained(evt);
            }
        });
        cpasswordJpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasswordJpfActionPerformed(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(102, 66, 41));
        jSeparator5.setForeground(new java.awt.Color(102, 66, 41));

        jSeparator9.setBackground(new java.awt.Color(102, 66, 41));
        jSeparator9.setForeground(new java.awt.Color(102, 66, 41));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(submitJbtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(accountJbtn))
                            .addComponent(nameJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(passwordJpf)
                            .addComponent(passwordJlbl)
                            .addComponent(emailJlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameJtf)
                            .addComponent(emailJtf)
                            .addComponent(confirmpasswordJlbl)
                            .addComponent(cpasswordJpf)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(signupJlbl)))
                .addGap(0, 86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(signupJlbl)
                .addGap(48, 48, 48)
                .addComponent(nameJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(passwordJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordJpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(confirmpasswordJlbl)
                .addGap(9, 9, 9)
                .addComponent(cpasswordJpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(emailJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitJbtn)
                    .addComponent(accountJbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 400, 510));

        jPanel1.setBackground(new java.awt.Color(4, 50, 34));

        welcomeJlbl.setBackground(new java.awt.Color(4, 50, 34));
        welcomeJlbl.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        welcomeJlbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeJlbl.setText("Welcome to Secure Access");

        welcome2Jlbl.setBackground(new java.awt.Color(4, 50, 34));
        welcome2Jlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        welcome2Jlbl.setForeground(new java.awt.Color(255, 255, 255));
        welcome2Jlbl.setText("Please provide some information");

        verifyPanel.setBackground(new java.awt.Color(4, 50, 34));
        verifyPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        emailJlbl2.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        emailJlbl2.setForeground(new java.awt.Color(255, 255, 255));
        emailJlbl2.setText("Verify your email");

        emailJlbl3.setBackground(new java.awt.Color(227, 238, 212));
        emailJlbl3.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        emailJlbl3.setForeground(new java.awt.Color(255, 255, 255));
        emailJlbl3.setText("EMAIL");

        emailJtf1.setBackground(new java.awt.Color(4, 50, 34));
        emailJtf1.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        emailJtf1.setForeground(new java.awt.Color(255, 255, 255));
        emailJtf1.setText("Enter your email");
        emailJtf1.setBorder(null);
        emailJtf1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailJtf1FocusGained(evt);
            }
        });
        emailJtf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailJtf1ActionPerformed(evt);
            }
        });

        verifyJbtn.setBackground(new java.awt.Color(255, 255, 255));
        verifyJbtn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        verifyJbtn.setForeground(new java.awt.Color(4, 50, 34));
        verifyJbtn.setText("VERIFY");
        verifyJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyJbtnActionPerformed(evt);
            }
        });

        otpJlbl.setBackground(new java.awt.Color(227, 238, 212));
        otpJlbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        otpJlbl.setForeground(new java.awt.Color(255, 255, 255));
        otpJlbl.setText("OTP");

        otpJtf.setBackground(new java.awt.Color(4, 50, 34));
        otpJtf.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        otpJtf.setForeground(new java.awt.Color(255, 255, 255));
        otpJtf.setText("Enter your OTP");
        otpJtf.setBorder(null);
        otpJtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                otpJtfFocusGained(evt);
            }
        });
        otpJtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpJtfActionPerformed(evt);
            }
        });

        sendOTPjbtn.setBackground(new java.awt.Color(255, 255, 255));
        sendOTPjbtn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        sendOTPjbtn.setForeground(new java.awt.Color(4, 50, 34));
        sendOTPjbtn.setText("SEND");
        sendOTPjbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendOTPjbtnActionPerformed(evt);
            }
        });

        cancelJbtn.setBackground(new java.awt.Color(255, 255, 255));
        cancelJbtn.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        cancelJbtn.setForeground(new java.awt.Color(4, 50, 34));
        cancelJbtn.setText("CANCEL");
        cancelJbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verifyPanelLayout = new javax.swing.GroupLayout(verifyPanel);
        verifyPanel.setLayout(verifyPanelLayout);
        verifyPanelLayout.setHorizontalGroup(
            verifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verifyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(verifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailJtf1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailJlbl3)
                    .addComponent(verifyJbtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(verifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cancelJbtn)
                    .addComponent(sendOTPjbtn))
                .addGap(25, 25, 25))
            .addGroup(verifyPanelLayout.createSequentialGroup()
                .addGroup(verifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verifyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(otpJtf, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(verifyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(otpJlbl))
                    .addGroup(verifyPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(emailJlbl2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        verifyPanelLayout.setVerticalGroup(
            verifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verifyPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(emailJlbl2)
                .addGap(32, 32, 32)
                .addGroup(verifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(verifyPanelLayout.createSequentialGroup()
                        .addComponent(sendOTPjbtn)
                        .addGap(30, 30, 30))
                    .addGroup(verifyPanelLayout.createSequentialGroup()
                        .addComponent(emailJlbl3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailJtf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(otpJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otpJtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(verifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyJbtn)
                    .addComponent(cancelJbtn))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(welcomeJlbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(welcome2Jlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(verifyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(welcomeJlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcome2Jlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verifyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJtfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailJtfActionPerformed

    private void nameJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJtfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameJtfActionPerformed

    private void passwordJpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordJpfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_passwordJpfActionPerformed

    private void nameJtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJtfFocusGained
        // TODO add your handling code here:
        //code for the "Enter your name" string to disappear once clicked
        //https://www.youtube.com/watch?v=-nWmjWA5cnY
        if (nameJtf.getText().equals("Enter your name")) {
            nameJtf.setText("");
            nameJtf.setForeground(new Color(169, 113, 66)); 
        }

    }//GEN-LAST:event_nameJtfFocusGained

    private void passwordJpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordJpfFocusGained
        // TODO add your handling code here:
        if (passwordJpf.getText().equals("Enter your password")) {
        passwordJpf.setText("");
        passwordJpf.setForeground(new Color(169, 113, 66)); 
        }

    }//GEN-LAST:event_passwordJpfFocusGained

    private void emailJtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailJtfFocusGained
        // TODO add your handling code here:
            if (emailJtf.getText().equals("Enter your email")) {
            emailJtf.setText("");
            emailJtf.setForeground(new Color(169, 113, 66)); 
}
    }//GEN-LAST:event_emailJtfFocusGained

    private void accountJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountJbtnActionPerformed
        // TODO add your handling code here:
        loginGUI myGUI = new loginGUI();
        myGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountJbtnActionPerformed

    private void cpasswordJpfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpasswordJpfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cpasswordJpfFocusGained

    private void cpasswordJpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasswordJpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpasswordJpfActionPerformed

    private void submitJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJbtnActionPerformed
        // TODO add your handling code here:
        //getting all inputs
        String name = nameJtf.getText();
        char[] password = passwordJpf.getPassword();
        char[] cPassword = cpasswordJpf.getPassword();
        String email = emailJtf.getText().toLowerCase();
       

        
         //Input validation
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter your name");
        } else if (password.length == 0) {
            JOptionPane.showMessageDialog(null, "Create password");
        } else if (cPassword.length == 0) {
            JOptionPane.showMessageDialog(null, "Confirm password");
        } else if (!Arrays.equals(password, cPassword)) {  //check if the passwords are equal
            JOptionPane.showMessageDialog(null, "Passwords do not match");
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter email address");
        } else {
            // All inputs are valid → just show the verify panel
            verifyPanel.setVisible(true);
            verifyPanel.revalidate();
            verifyPanel.repaint();
        }
        
        if (!Arrays.equals(password, cPassword)) {  
        JOptionPane.showMessageDialog(null, "Passwords do not match");
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter email address");
        } else {
            // --- STAGE 1 SUCCESS: Store data and hash password ---
            tempName = name;
            tempEmail = email;
            tempPassword = password; // Temporarily store the password array

            // Show the verify panel to proceed with OTP verification
            verifyPanel.setVisible(true);
            emailJtf1.setText(tempEmail); // Pre-fill the email for verification

            //don't hash/save yet. saving that for the verify button.
        }
       
    }//GEN-LAST:event_submitJbtnActionPerformed

    private void emailJtf1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailJtf1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJtf1FocusGained

    private void emailJtf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailJtf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailJtf1ActionPerformed

    private void verifyJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyJbtnActionPerformed
        // TODO add your handling code here:
        String enteredOTP = otpJtf.getText().trim(); 

        // Input validation
        if (enteredOTP.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the OTP.");
        }

//        if (enteredOTP.equals(generateOTP)) {
//            JOptionPane.showMessageDialog(this, "Verification successful! You can now complete signup.");
//            verifyPanel.setVisible(false);
//            // 1. Hash the password (must be done now)
//            String hashedPassword = Hashing.hashPassword(tempPassword); 
//
//            // 2. Clear the plaintext password from memory immediately
//            Arrays.fill(tempPassword, ' ');
//
//            if (hashedPassword != null) {
//                // 3. Save the user data using DBhelper
//                boolean saved = DBhelper.saveUser(tempName, tempEmail, hashedPassword); 
//
//                if (saved) {
//                    JOptionPane.showMessageDialog(this, "Account created successfully! You can now log in.");
//
//                    // 4. Redirect to the login screen
//                    loginGUI myGUI = new loginGUI();
//                    myGUI.setVisible(true);
//                    this.dispose(); 
//                } else {
//                    // This usually happens if the email already exists (UNIQUE constraint error)
//                    JOptionPane.showMessageDialog(this, "Error: Account creation failed. Email may already be in use.", "DB Error", JOptionPane.ERROR_MESSAGE);
//                }
//            } else {
//                JOptionPane.showMessageDialog(this, "Error: Could not hash password. Registration failed.", "Security Error", JOptionPane.ERROR_MESSAGE);
//            }
//            verifyPanel.setVisible(false);
//        } else {
//            JOptionPane.showMessageDialog(this, "Invalid OTP. Please try again.");
//        }

        if (enteredOTP.equals(generateOTP)) {
        
            // --- SUCCESSFUL VERIFICATION - PERFORM FINAL DB SAVE ---

            // 1. Generate the salt
            String salt = Hashing.generateSaltBase64(); 

            // 2. Hash the password WITH the salt (Hashing method clears tempPassword array)
            String hashedPassword = null;
            try {
                hashedPassword = Hashing.hashPassword(tempPassword, salt); 
            } catch (IllegalStateException e) {
                JOptionPane.showMessageDialog(this, "Security Error: Failed to hash password.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // tempPassword array is now cleared by Hashing.hashPassword()

            if (hashedPassword != null) {
                // 3. Save the user data using the new saveUser signature
                boolean saved = DBhelper.saveUser(tempName, tempEmail, hashedPassword, salt); // ADD SALT

                if (saved) {
                    JOptionPane.showMessageDialog(this, "Account created successfully! You can now log in.");
                    loginGUI myGUI = new loginGUI();
                    myGUI.setVisible(true);
                    this.dispose(); 
                } else {
                    JOptionPane.showMessageDialog(this, "Error: Account creation failed. Email may already be in use.", "DB Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Invalid OTP. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_verifyJbtnActionPerformed

    private void otpJtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_otpJtfFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_otpJtfFocusGained

    private void otpJtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpJtfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otpJtfActionPerformed

    private void sendOTPjbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendOTPjbtnActionPerformed
        // TODO add your handling code here:
        String userEmail = emailJtf1.getText().trim();

        if (userEmail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email");
            return;
        }
        // Generate a 6-digit OTP
        generateOTP = generateOTP(6);

        // Saving the OTP to a text file
        try (FileWriter writer = new FileWriter("otpcode.txt")) {
            writer.write("Your verification code is: " + generateOTP);
            writer.flush();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error writing OTP file: " + e.getMessage());
            return;
        }

        JOptionPane.showMessageDialog(null, "A verification code has been saved to 'otpcode.txt'.\n"
                + "Please open the file and enter the code below to verify your account.");

    }//GEN-LAST:event_sendOTPjbtnActionPerformed

    private void cancelJbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJbtnActionPerformed
        // TODO add your handling code here:
        if (verifyPanel.isVisible()) {
            // If the panel is visible, hide it
            verifyPanel.setVisible(false);
        } else {
            // If the panel is not visible, show it
            verifyPanel.setVisible(true);
        }
    }//GEN-LAST:event_cancelJbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signupGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signupGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountJbtn;
    private javax.swing.JButton cancelJbtn;
    private javax.swing.JLabel confirmpasswordJlbl;
    private javax.swing.JPasswordField cpasswordJpf;
    private javax.swing.JLabel emailJlbl;
    private javax.swing.JLabel emailJlbl2;
    private javax.swing.JLabel emailJlbl3;
    private javax.swing.JTextField emailJtf;
    private javax.swing.JTextField emailJtf1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel nameJlbl;
    private javax.swing.JTextField nameJtf;
    private javax.swing.JLabel otpJlbl;
    private javax.swing.JTextField otpJtf;
    private javax.swing.JLabel passwordJlbl;
    private javax.swing.JPasswordField passwordJpf;
    private javax.swing.JButton sendOTPjbtn;
    private javax.swing.JLabel signupJlbl;
    private javax.swing.JButton submitJbtn;
    private javax.swing.JButton verifyJbtn;
    private javax.swing.JPanel verifyPanel;
    private javax.swing.JLabel welcome2Jlbl;
    private javax.swing.JLabel welcomeJlbl;
    // End of variables declaration//GEN-END:variables
}
